### ISSUE TITLE
Why is the clearcoat layering using the max of the two Fresnel terms max(Fresnel(v . Nc), Fresnel(l . Nc))

### ISSUE THREAD

**Issue by TomClabault** [DassaultSystemes-Technology/EnterprisePBRShadingModel#39]
[Equation 72](https://dassaultsystemes-technology.github.io/EnterprisePBRShadingModel/spec-2025x.md.html#mjx-eqn-72) of the spec uses `max(Fc(v . Nc), Fc(l . Nc))` to compute the amount of energy that is passed to the glittery core.

A few questions about that to try and understand things better:

1) Why is it using the "geometric normal" `Nc` instead of the microfacet normal of the coat `Hr`?
2) Is it correct that `Fresnel(v . Nc)` represents the amount of light that doesn't hit total internal reflection at the coat/air interface on its way back from the glittery core?
3) `Fresnel(l . Nc)` must be the amount of light that passes through the coat and reaches the glittery core. Why not use `1.0f - Fresnel(l . Hr)`? (similar question to 1) I guess)
4) Why use the `max()` of 2) and 3) instead of the product of the two?
5) Why do we not have this `max()` approach (or even the product of the two fresnel terms, question 4)) used for the dielectric layer on top of the diffuse base? How is a dielectric microfacet layer on top of a diffuse base different from a coat layer on top of a glittery core with regards to the fresnel terms used to compute the amount of energy that is passed to/gets back from the layer below ?

**Comment by bsdorra** [comment]
1. `Nc` is the clearcoat (shading) normal
2. The clearcoat model is assumed to be thin, it doesn't consider interactions between layers. `Fresnel(v . Nc)` and `Fresnel(l . Nc)` are really just the Fresnel terms for light and view direction based on the clearcoat normal.
3. `1.0 - c*max(Fresnel(v . Nc), Fresnel(l . Nc))` is the fraction of light that passes through to the base layer. Using the clearcoat normal instead of the half vector ensures that the layering is energy conserving (doesn't produce energy). It is not energy preserving though, especially for higher roughness values darkening will occur. The assumption here is that high roughness clearcoat is rather unlikely in real use-cases so we went with the simple approach. 
4. Using the maximum of the two terms is a conservative bound so that the energy scaling also works with bi-directional rendering techniques, in exchange for minimal over compensation that results in slight darkening.
5. The dielectric layering uses a more sophisticated approach that ensures energy conservation **and** preservation (also uses multi-scatter ggx).

Here's a [blog post](https://0xef.wordpress.com/2020/05/01/physically-based-materials-energy-conservation-and-reciprocity/) that has some details on usage of different Fresnel terms for the layering.

**Comment by TomClabault** [comment]
Perfect, that answers all my questions! Thanks!
